### ISSUE TITLE
Discuss the Device API

### ISSUE THREAD

**Issue by astralien3000** [astralien3000/aversive--#50]
The use of `setValue` and `getValue` for every device may be a problem. Indeed, for example, in Streams, setValue/getValue cans be replaced by putChar/getChar or something like that, which are more explicit about what it does. The same could be said for some other devices.

Moreover, the `{set,get}Value` interface seem to be more difficult to manage with devices like RDS, which has to return a list !

**Comment by astralien3000** [comment]
Erf, I just had a thought.
It may be better to name `setValue` in `setDeviceInput`,
and `getValue` in `getDeviceOutput`.

Because this is how one can represents a device : 
```
          +--------+
INPUT --> | Device | --> OUTPUT
          +--------+
```

If it is a actuator, here is the "stream" : 
```
        +--------+
APP --> | Device | --> REAL WORLD
        +--------+
```
So, we can see that it is the input that is set.

The same thing can be said with a sensor :
```
        +--------+
APP <-- | Device | <-- REAL WORLD
        +--------+
```
The output of the device is retrieved.

The problem did not exists with `getValue` and `setValue`... And I dont know if it is better like this.

**Comment by benoit-gilbert** [comment]
At first I didn't understand what you mean   and tough right term should be getDeviceInput and setDeviceOutput but as we are outside the device, it's as you said setDeviceInput and getDeviceOutput.
And it's really clearer than before (for a noob like me)
________________________________
De : Loïc Dauphin<mailto:notifications@github.com>
Envoyé : ‎06/‎07/‎2015 11:26
À : astralien3000/aversive--<mailto:aversive--@noreply.github.com>
Objet : Re: [aversive--] Discuss the Device API (#50)

Erf, I just had a thought.
It may be better to name `setValue` in `setDeviceInput`,
and `getValue` in `getDeviceOutput`.

Because this is how one can represents a device :
```
          +--------+
INPUT --> | Device | --> OUTPUT
          +--------+
```

If it is a actuator, here is the "stream" :
```
        +--------+
APP --> | Device | --> REAL WORLD
        +--------+
```
So, we can see that it is the input that is set.

The same thing can be said with a sensor :
```
        +--------+
APP <-- | Device | <-- REAL WORLD
        +--------+
```
The output of the device is retrieved.

The problem did not exists with `getValue` and `setValue`... And I dont know if it is better like this.

---

**Comment by astralien3000** [comment]
I'm glad you agree with me ^^ !
Since Elioty doesn't seem to be certain, there is an other interesting case : 
```
           +------+                          +------+
INPUT1 --> | DEV1 | --> OUTPUT1 = INPUT2 --> | DEV2 | --> OUTPUT2
(APP)      +------+                          +------+     (REAL WORLD)
```
For an actuator, but the problem is the same for the sensor.
(For example, DEV1 can be a MotorController, and DEV2 can be a Motor)

I think the problem about saying `DEV1.setOutput` is that the user could think that `OUTPUT1` is set. And actually, `INPUT1` is set, and DEV1 can compute `OUTPUT1` to send it to `DEV2`.

An other avantage of the name `DEV1.setDeviceInput` is that you can say `DEV1.getDeviceInput` to get the last value the application sent to the device (`INPUT1`), and say `DEV1.getDeviceOutput` to get the last value the device computed (`OUTPUT1`).

With the name `DEV1.setOutput`, you would say `DEV1.getOutput`, wich is tricky since the user may think that the value `OUTPUT1` is retrieved, or think that the `INPUT1` value is retrieved...

**Comment by Elioty** [comment]
I am still not sure about all of this. This looks tricky to me but that's may be because I am too used to the old (and still current) way. So let me think of it some more.

**Comment by Elioty** [comment]
By the way, just checked it to be sure. A controller (either Motor or Robot) is not a device, it inherits `Output` though.

**Comment by astralien3000** [comment]
`getValue` and `setValue` ? I don't think it is incompatible. It depends if in your head, you think "get an input value from this sensor" or "get the output value of this sensor". For an actuator : "set the output value to this actuator" or "set the input value of this actuator".

If you agree with me, the first way to think would be represented as this (for an actuator) : 
```
       +--------------+
APP ---| OutputDevice |---> REAL WORLD
       +--------------+
```
And the second as this : 
```
          +--------------+
INPUT --> | OutputDevice | --> OUTPUT
  APP     +--------------+     REAL WORLD
```

In the first case, it seems that you can't clearly separate the input of the device and the output of the device, because the device is considered as the output of your application. It is not bad, but if the user want to represent it's devices as blocks (as in the asserv schematics), he may want to know the input and output values of a block. It could be useful for debugging. 

And yes, a lot of devices don't inherits from `Device` class.
Indeed, this class is used mainly to interface with SASIAE, and should be a parent of `Input` and `Output`. But it could create a [diamond problem](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem) with devices that can be input or output.
But these should be called "devices" anyway. The difference is that a controller (for example) is a "virtual device", and a (real) motor is a "device".
Maybe the `Device` class should be renamed in something like `IOInterface` or `InterfaceDevice` (I don't know a good name for this...)... Our/my bad ?

**Comment by astralien3000** [comment]
Oups...

**Comment by Elioty** [comment]
Ok so after further discussion today, we (astralien3000 and I) agreed on this:

We would have two interfaces `AbstractSensor<T>` and `AbstractActuator<T>` with respectively the methods `T getValue() const` and `void setInput(const T&)`. Moreover, we would completely remove the class `Device` so the user of the API no longer has to provide a device name as it is useless anyway in almost every use case. The name was used only with the SASIAE implementation. From now on, the device name will be determined internally (to communicate with the simulator, so only within the SASIAE implementation) according to the concrete device characteristics, for example, the pin number for a pin, the timer id for a quadratic encoder, etc.

Did I forget anything?

**Comment by astralien3000** [comment]
I don't think so.

What a short conclusion for a so long discussion... I am almost disappointed !

**Comment by Elioty** [comment]
Well, you know it is important to be able to clearly synthesise decisions as an engineer :yum:
