### ISSUE TITLE
Make use of C++11 new type alias syntax instead of typedef

### ISSUE THREAD

**Issue by Elioty** [astralien3000/aversive--#68]
Reference: http://en.cppreference.com/w/cpp/language/type_alias

Personally, I find this new syntax way more readable than a typedef. I never remember in which order I should write my type's names in a typedef declaration but the type alias declaration is way clearer with its regular assignment sort of syntax.
Also, major upside, type alias can be template! Example:

``` C++
template<typename T> typedef Array<T> NewName; // invalid
template<typename T> using NewName = Array<T>; // valid
// usage:
NewName<int> myIntArray;
```

And of course, this new syntax is still properly scoped if used in a namespace, a struct, a class or a function.

**Comment by astralien3000** [comment]
Cool !
I did not know C++11 could do that.
I would also rather use this than the typedef syntax.
