### ISSUE TITLE
Participative documentation

### ISSUE THREAD

**Issue by astralien3000** [astralien3000/aversive--#79]
It would be great to enable the users to ask for more explanation on a function/class/... simply by clicking on a button in the documentation web site.

It is just an idea, I don't know if a tool can do this (It would be cool !)

The aim is to know what is the most demanded part of the documentation, and if this part is well explained.

**Comment by Elioty** [comment]
No clue how we can properly insert things in the HTML files generated  by Doxygen but I think it would just need to be a button/link that redirects the user to a kind of contact form where the user can leave a message about the problem (for spelling, grammar or simply technical mistakes) or what need to be more explained. And the submission would also save the URL of the page the user clicked on the button from.
