### ISSUE TITLE
Proof that C++ is the best !

### ISSUE THREAD

**Issue by astralien3000** [astralien3000/aversive--#84]
We need a benchmark that proves that C++ HAL and HDL calls are (strictly) equivalent to avr-libc/io code (and CMSIS, for arm-based microcontrollers).

Actually, I think we need this benchmark for each architecture supported.
Maybe it is not compulsori to do this for each microcontroller however ? I don't really know.

**Comment by aethaniel** [comment]
+1
Eager to see the results!

**Comment by astralien3000** [comment]
Yes !
Actually, I have already some good results on AVR targets, but nothing clean enough to be shown ^^
I just fear a little the ARM architecture, which I did not test currently. But since the compiler remains GCC, there should not be any problem.
