### ISSUE TITLE
Generating an error for some warnings (not all)

### ISSUE THREAD

**Issue by astralien3000** [astralien3000/aversive--#91]
I have found this option for the compiler : 

```
-Werror=$(warning)
```

Where `$(warning)` is the name of the warning which should throw an error.

So, we can use this option for the HAL interface : 
-Werror=deprecated-declarations
So that the constants will also throw errors when used !

**Comment by Elioty** [comment]
Oh great, I knew `-Werror` but it turns **every** warnings into errors. Maybe we would prefer that behaviour though. I tend to say that warnings are not good at all and should be taken care of asap in bare-metal embedded software.
